gathering avg returns for each security, average risk, and correlation between each pair

In [20]:
import numpy as np
import pandas as pd

In [23]:

df = pd.read_csv("Weekly1-5.csv")

# Skip the first row which contains repeated headers
df_cleaned = df.iloc[1:].reset_index(drop=True)

# Extract each pair of Date and Close as its own table
AAPL = df_cleaned.iloc[:, [0, 1]].rename(columns={df.columns[0]: 'Date', df.columns[1]: 'Close'})
MSFT = df_cleaned.iloc[:, [3, 4]].rename(columns={df.columns[3]: 'Date', df.columns[4]: 'Close'})
NVDA = df_cleaned.iloc[:, [6, 7]].rename(columns={df.columns[6]: 'Date', df.columns[7]: 'Close'})
HD   = df_cleaned.iloc[:, [9, 10]].rename(columns={df.columns[9]: 'Date', df.columns[10]: 'Close'})
COST = df_cleaned.iloc[:, [12, 13]].rename(columns={df.columns[12]: 'Date', df.columns[13]: 'Close'})

# Optionally convert Close to numeric and Date to datetime
for stock in [AAPL, MSFT, NVDA, HD, COST]:
    stock['Date'] = pd.to_datetime(stock['Date'])
    stock['Close'] = pd.to_numeric(stock['Close'])

# Example: display AAPL data
AAPL['returns'] = AAPL['Close'].pct_change()
MSFT['returns'] = MSFT['Close'].pct_change()
NVDA['returns'] = NVDA['Close'].pct_change()
HD['returns'] = HD['Close'].pct_change()
COST['returns'] = COST['Close'].pct_change()
display(MSFT)

                  Date   Close   returns
0  2025-01-10 16:00:00  418.95       NaN
1  2025-01-17 16:00:00  429.03  0.024060
2  2025-01-24 16:00:00  444.06  0.035033
3  2025-01-31 16:00:00  415.06 -0.065306
4  2025-02-07 16:00:00  409.75 -0.012793
5  2025-02-14 16:00:00  408.43 -0.003221
6  2025-02-21 16:00:00  408.21 -0.000539
7  2025-02-28 16:00:00  396.99 -0.027486
8  2025-03-07 16:00:00  393.31 -0.009270
9  2025-03-14 16:00:00  388.56 -0.012077
10 2025-03-21 16:00:00  391.26  0.006949
11 2025-03-28 16:00:00  378.80 -0.031846
12 2025-04-04 16:00:00  359.84 -0.050053
13 2025-04-11 16:00:00  388.45  0.079508
14 2025-04-17 16:00:00  367.78 -0.053211
15 2025-04-25 16:00:00  391.85  0.065447
16 2025-05-02 16:00:00  435.28  0.110833

In [7]:
def get_var_name(var):
    for name, obj in globals().items():
        if obj is var:
            return name
    return None

In [24]:
#stock covariance 
#initialize matrix
sigma = np.zeros((5,5),dtype=float)
stocks = [AAPL,MSFT, NVDA, HD, COST]
for j in range(len(stocks)):
    ar = np.average(stocks[j]['returns'].dropna())
    print(get_var_name(stocks[j]))
    v = np.zeros((5),dtype=float)
    for i in range(len(stocks)):
        avgReturn_other = np.average(stocks[i]['returns'].dropna())
        otherDiffs = [x-avgReturn_other for x in stocks[i]['returns'].dropna()]
        mainDiffs = [x-ar for x in stocks[j]['returns'].dropna()]
        cov = sum([a*b for a,b in zip(otherDiffs,mainDiffs)])/len(AAPL)
        # print(cov)
        v[i] = cov
        
    print(v)
    sigma[j] = v
print(sigma)

AAPL
[0.00288025 0.00059985 0.00102682 0.00040614 0.00075636]
MSFT
[0.00059985 0.00213673 0.00294226 0.00030942 0.00011504]
NVDA
[0.00102682 0.00294226 0.00779897 0.00010137 0.0005807 ]
HD
[0.00040614 0.00030942 0.00010137 0.00088364 0.00068422]
COST
[0.00075636 0.00011504 0.0005807  0.00068422 0.00140397]
[[0.00288025 0.00059985 0.00102682 0.00040614 0.00075636]
 [0.00059985 0.00213673 0.00294226 0.00030942 0.00011504]
 [0.00102682 0.00294226 0.00779897 0.00010137 0.0005807 ]
 [0.00040614 0.00030942 0.00010137 0.00088364 0.00068422]
 [0.00075636 0.00011504 0.0005807  0.00068422 0.00140397]]

In [13]:

m = np.zeros(5)
for i in range(len(stocks)):
    average_return = np.average(stocks[i]['returns'].dropna())
    name = get_var_name(stocks[i])
    print(name,f"{average_return:.4f}")
    m[i] = average_return
print(m)

AAPL -0.0073
MSFT 0.0035
NVDA -0.0065
HD -0.0037
COST 0.0054
[-0.00729508  0.00350164 -0.00648644 -0.00371819  0.00535392]